{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "Header_DeleteConfirmation"
	},
	"Message": "Delete current entity?",
	"Title": "Delete Confirmation",
	"OKCaption": "OK",
	"CancelCaption": "Cancel"
}