{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "navToCreateItem"
	},
	"PageToOpen": "/carcarenew/Pages/CreateItem.page",
	"ModalPage": true,
	"Transition": {
		"Curve": "EaseIn",
		"Name": "None"
	}
}